export const GET_ALL_JOBS = "GET_ALL_JOBS";
export const GET_DETAIL_JOB_BY_ID = "GET_DETAIL_JOB_BY_ID";
export const GET_JOBS_CREATE_BY_COMPANY = "GET_JOBS_CREATE_BY_COMPANY";
export const SEARCH_JOBS = "SEARCH_JOBS";
